# Generated by Django 4.0.4 on 2022-04-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('link', models.CharField(blank=True, default='', max_length=200)),
                ('updated', models.DateTimeField()),
                ('summary', models.TextField()),
                ('content', models.TextField()),
            ],
            options={
                'ordering': ['updated'],
            },
        ),
    ]
